### ISSUE TITLE
Does this allow to connect any remote mongodb?

### ISSUE THREAD

**Issue by rakeshnambiar** [rjmasikome/mongo-prometheus#1]
Does this allow to connect any remote mongodb? If yes, could you please guide how to add the servername, username and password etc.

**Comment by rjmasikome** [comment]
Hey yeah sure, you can pack it up in the config by passing a uri parameter there: https://github.com/rjmasikome/mongo-prometheus/blob/master/lib/MongoPrometheus.ts#L19

**Comment by rakeshnambiar** [comment]
That's great. I will try it out.
